version: "2"

linters:
  enable:
    - gocritic
    - revive
    - misspell
  settings:
    revive:
      rules:
        - name: blank-imports
        - name: exported
        - name: unused-parameter
        - name: unreachable-code
