version: 2

builds:
  - main: ./cmd/daggle/main.go
    binary: daggle
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/cynkra/daggle/cli.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "daggle_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
